---
AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon EKS - Node Group
Parameters:
  ClusterVersion:
    Description: Cluster Version
    Type: String
    Default: "1.16"
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC of the worker instances
    Default: vpc-05a0e9043c8e410ad
  EnvironmentName:
    Type: String
    Description: Env name
  EKSSubnetZoneAPrivate:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the public subnet in Availability Zone 1 in your existing VPC (e.g., subnet-a0246dcd)
    Default: subnet-0d668d443caaed0fb
  EKSSubnetZoneBPrivate:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the public subnet in Availability Zone 2 in your existing VPC (e.g., subnet-b1236eea)
    Default: subnet-08e031bfd77d59881
  EKSSubnetZoneCPrivate:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the public subnet in Availability Zone 3 in your existing VPC (e.g., subnet-c3456aba)
    Default: subnet-040375892a2bb9ad2
  EKSClusterName:
    Type: String
    Description: The EKS Cluster Name
    Default: 'test-env'
  EKSControlPlaneSecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: The ID of the public subnet in Availability Zone 3 in your existing VPC (e.g., subnet-c3456aba)
    Default: sg-03586eb75022361bb

Resources:
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: test-env
      NodeRole: 'arn:aws:iam::658049716057:role/neweksworkernodes'
      InstanceTypes:
        - "m4.2xlarge"
      ScalingConfig:
        MinSize: 1
        DesiredSize: 3
        MaxSize: 5
      Subnets:
        - !Ref EKSSubnetZoneAPrivate
        - !Ref EKSSubnetZoneBPrivate
        - !Ref EKSSubnetZoneCPrivate

Outputs:
  EKSNodeGroupName:
    Description: The EKS NodeGroup name
    Value: !Ref EKSNodegroup
